/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_louis_shark_qqvoice_VoiceFixer */

#ifndef _Included_cn_louis_shark_qqvoice_VoiceFixer
#define _Included_cn_louis_shark_qqvoice_VoiceFixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_louis_shark_qqvoice_VoiceFixer
 * Method:    fix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_louis_shark_qqvoice_VoiceFixer_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
